<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RAJENDRA" failures="0" tests="9" name="loginlogoutscenario.Assignments5" time="20.392" errors="1" timestamp="2022-11-13T00:32:53 IST" skipped="0">
  <testcase classname="loginlogoutscenario.Assignments5" name="launchbrowser" time="1.829"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="navigation" time="6.076"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="login" time="6.256"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="opentask" time="5.635"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="createcustomer" time="0.000">
    <error message="
Method private static void loginlogoutscenario.Assignments5.createcustomer(java.lang.String) requires a @DataProvider named : createcustomer" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method private static void loginlogoutscenario.Assignments5.createcustomer(java.lang.String) requires a @DataProvider named : createcustomer
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createcustomer -->
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="modifyuser" time="0.047"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="deletecustomer" time="0.048"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="logout" time="0.289"/>
  <system-out/>
  <testcase classname="loginlogoutscenario.Assignments5" name="closeapp" time="0.212"/>
  <system-out/>
</testsuite> <!-- loginlogoutscenario.Assignments5 -->
